from enum import StrEnum


class TaskType(StrEnum):
    BUILD_RESOLVE = "build-resolve"
    SDK_ANALYZE = "sdk-analyze"


class TaskStatus(StrEnum):
    COMPLETED = "completed"
    VALIDATION_FAILED = "validation_failed"
    TIMEOUT = "timeout"
    MODEL_ERROR = "model_error"
    BUDGET_EXCEEDED = "budget_exceeded"
    UNSAFE_OUTPUT = "unsafe_output"
    EMPTY_RESULT = "empty_result"


class FailureCode(StrEnum):
    INVALID_SCHEMA = "INVALID_SCHEMA"
    INVALID_GROUNDING = "INVALID_GROUNDING"
    TIMEOUT = "TIMEOUT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    TOKEN_BUDGET_EXCEEDED = "TOKEN_BUDGET_EXCEEDED"
    MAX_STEPS_EXCEEDED = "MAX_STEPS_EXCEEDED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ALL_TOOLS_EXHAUSTED = "ALL_TOOLS_EXHAUSTED"
    UNSAFE_CONTENT = "UNSAFE_CONTENT"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    LLM_OVERLOADED = "LLM_OVERLOADED"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    UNKNOWN_TASK_TYPE = "UNKNOWN_TASK_TYPE"
    MISSING_BUILD_MATERIALS = "MISSING_BUILD_MATERIALS"
    SDK_MISMATCH = "SDK_MISMATCH"
    BUILD_SCRIPT_SYNTHESIS_FAILED = "BUILD_SCRIPT_SYNTHESIS_FAILED"
    COMPILE_FAILED = "COMPILE_FAILED"
    EXPECTED_ARTIFACTS_MISMATCH = "EXPECTED_ARTIFACTS_MISMATCH"
